name: StaticWorld
version: "${pom.version}"
api: ["3.0.0"]
main: org.powernukkitx.staticworld.StaticWorld
author: "Buddelbubi"
description: "Lock down your world to certain chunks so you save memory"
softdepend:
  - SimpleWorldEdit
