name: StaticWorld
version: "1.0"
api: ["2.0.0"]
main: org.powernukkitx.staticworld.StaticWorld
author: "Buddelbubi"
description: "Lock down your world to certain chunks so you save memory"
softdepend:
  - SimpleWorldEdit